-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bioma
(
    id_bioma integer NOT NULL,
    bioma_declarado text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bioma_pkey PRIMARY KEY (id_bioma)
);

CREATE TABLE IF NOT EXISTS public.categoria_manejo
(
    id_manejo integer NOT NULL,
    categoria_de_manejo text COLLATE pg_catalog."default" NOT NULL,
    categoria_iucn text COLLATE pg_catalog."default" NOT NULL,
    plano_de_manejo text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_manejo_pkey PRIMARY KEY (id_manejo)
);

CREATE TABLE IF NOT EXISTS public.coleta_de_lixo
(
    id_mutirao integer NOT NULL,
    plastico integer,
    borracha integer,
    madeira integer,
    produtos_texteis integer,
    papel integer,
    metal integer,
    vidro integer,
    materiais_de_pesca integer,
    outros_residuos integer,
    CONSTRAINT coleta_de_lixo_pkey PRIMARY KEY (id_mutirao)
);

CREATE TABLE IF NOT EXISTS public.esfera_administrativa
(
    id_esfera integer NOT NULL,
    esfera_administrativa text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT esfera_administrativa_pkey PRIMARY KEY (id_esfera)
);

CREATE TABLE IF NOT EXISTS public.instituicao_organizadora
(
    id_instituicao_organizadora integer NOT NULL,
    instituicao_organizadora text COLLATE pg_catalog."default" NOT NULL,
    carater_da_instituicao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT instituicao_organizadora_pkey PRIMARY KEY (id_instituicao_organizadora)
);

CREATE TABLE IF NOT EXISTS public.local_de_coleta
(
    id_mutirao integer NOT NULL,
    nome_do_local text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT local_de_coleta_pkey PRIMARY KEY (id_mutirao)
);

CREATE TABLE IF NOT EXISTS public.municipio
(
    id_municipio integer NOT NULL,
    cidade text COLLATE pg_catalog."default" NOT NULL,
    estado text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT municipio_pkey PRIMARY KEY (id_municipio)
);

CREATE TABLE IF NOT EXISTS public.mutirao_de_limpeza
(
    id_mutirao integer NOT NULL,
    data_do_mutirao date NOT NULL,
    horario_de_inicio time without time zone NOT NULL,
    numero_aproximado_de_participantes integer,
    duracao_total time without time zone NOT NULL,
    id_municipio integer,
    id_instituicao_organizadora integer,
    CONSTRAINT mutirao_de_limpeza_pkey PRIMARY KEY (id_mutirao)
);

CREATE TABLE IF NOT EXISTS public.tipo_de_lixo
(
    id_mutirao integer NOT NULL,
    fragmentos_de_plastico integer,
    canudos integer,
    embalagens_de_alimento integer,
    garrafas_pet integer,
    sacolas integer,
    pneus integer,
    preservativos integer,
    embalagens_de_cigarro integer,
    jornais_panfletos_revistas_livros integer,
    latas integer,
    entulhos integer,
    animais_mortos integer,
    CONSTRAINT tipo_de_lixo_pkey PRIMARY KEY (id_mutirao)
);

CREATE TABLE IF NOT EXISTS public.unidade_de_conservacao
(
    id_uc integer NOT NULL,
    nome_da_uc text COLLATE pg_catalog."default" NOT NULL,
    ano_de_criacao integer,
    area_soma_biomas double precision,
    area_soma_biomas_continentais double precision,
    area_marinha double precision,
    id_bioma integer,
    id_municipio integer,
    id_manejo integer,
    id_esfera integer,
    CONSTRAINT unidade_de_conservacao_pkey PRIMARY KEY (id_uc)
);

ALTER TABLE IF EXISTS public.coleta_de_lixo
    ADD CONSTRAINT coleta_de_lixo_id_mutirao_fkey FOREIGN KEY (id_mutirao)
    REFERENCES public.mutirao_de_limpeza (id_mutirao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS coleta_de_lixo_pkey
    ON public.coleta_de_lixo(id_mutirao);


ALTER TABLE IF EXISTS public.local_de_coleta
    ADD CONSTRAINT local_de_coleta_id_mutirao_fkey FOREIGN KEY (id_mutirao)
    REFERENCES public.mutirao_de_limpeza (id_mutirao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS local_de_coleta_pkey
    ON public.local_de_coleta(id_mutirao);


ALTER TABLE IF EXISTS public.mutirao_de_limpeza
    ADD CONSTRAINT mutirao_de_limpeza_id_instituicao_organizadora_fkey FOREIGN KEY (id_instituicao_organizadora)
    REFERENCES public.instituicao_organizadora (id_instituicao_organizadora) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mutirao_de_limpeza
    ADD CONSTRAINT mutirao_de_limpeza_id_municipio_fkey FOREIGN KEY (id_municipio)
    REFERENCES public.municipio (id_municipio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tipo_de_lixo
    ADD CONSTRAINT tipo_de_lixo_id_mutirao_fkey FOREIGN KEY (id_mutirao)
    REFERENCES public.coleta_de_lixo (id_mutirao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS tipo_de_lixo_pkey
    ON public.tipo_de_lixo(id_mutirao);


ALTER TABLE IF EXISTS public.unidade_de_conservacao
    ADD CONSTRAINT unidade_de_conservacao_id_bioma_fkey FOREIGN KEY (id_bioma)
    REFERENCES public.bioma (id_bioma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.unidade_de_conservacao
    ADD CONSTRAINT unidade_de_conservacao_id_esfera_fkey FOREIGN KEY (id_esfera)
    REFERENCES public.esfera_administrativa (id_esfera) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.unidade_de_conservacao
    ADD CONSTRAINT unidade_de_conservacao_id_manejo_fkey FOREIGN KEY (id_manejo)
    REFERENCES public.categoria_manejo (id_manejo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.unidade_de_conservacao
    ADD CONSTRAINT unidade_de_conservacao_id_municipio_fkey FOREIGN KEY (id_municipio)
    REFERENCES public.municipio (id_municipio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;